version: '3'
services:
  my-archive:
    build:
      context: .
      dockerfile: Dockerfile
    image: rrhan0/my-archive:latest
    container_name: my-archive
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: